# environment
environment:
  nodejs_version: "8"
  
platform:
  - x86

install:
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm remove -g autorest
  - npm install dotnet-sdk-2.0.0@1.4.3 --verbose 


# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - tests

# image to use      
image: Visual Studio 2017

build_script:
  - ps: .\build\testpackage.ps1
