# version format
version: 1.0.{build}-{branch}
# image to use      
image: Visual Studio 2017

# environment
environment:
  nodejs_version: "8"
  
platform:
  - x86

install:
  - docker 
  - git submodule update --init --recursive

build_script:
  - docker build -t agoda/autorest

# branches to build
branches:
  # whitelist
  only:
    - master
    - tests

