version: "3"

services:
  autorest-gen: 
    image: reg-hk.agodadev.io/library/autorest-gen:${IMAGE_VERSION}
    ### Following commented out lines are helpful for local testing
    ### Build image from local docker file
    # build: .
    ### Get generated code to local to view .cs and .nupkg file
    ### you can change .nupkg to .zip to view generated .dll file inside the package
    # volumes:
    #   - C:/New folder/output4:/app/output
    environment: 
      ENV_YML_FILE_URL: ${SWAGGER_URL}
      ENV_OUTPUT_PATH: "/app/output"
      ENV_NAMESPACE: ${NAMESPACE} 
      ENV_VERSION: ${VERSION}
      ENV_NUGET_KEY: ${NUGET_KEY}
      ENV_SHOULD_PUSH_NUGET: ${SHOULD_UPLOAD_TO_NUGET} 
      # To test on local
      #ENV_YML_FILE_URL: "https://github.agodadev.io/raw/IT-Platform/customer-api/7edb9cafd6482334558be1f523e67a4318d364c3/src/main/resources/openapi.yml?token=AAAAAYM5MMNJGIJKNLLRQH26TVPLY"
      #ENV_NAMESPACE: Agoda.CustomerApi.Client.V2
      #ENV_VERSION: 2.0.25
      #ENV_NUGET_KEY: "5a77e143-0230-4db3-b23c-726b91f2a347"
      #ENV_SHOULD_PUSH_NUGET: "false"
    command: /app/build/create-project.sh
